GET http://localhost:8000/api/test
###
GET http://localhost:8000/api/employees 
###
POST http://localhost:8000/api/employees
Content-Type: application/json

{
    "first_name": "Peter",
    "last_name": "Pan",
    "email": "peter.pan@example.com",
    "gender": "Male",
    "birthday": "1991-01-01",
    "date_hired": "2021-01-01",
    "salary": 40000
}
###
GET http://localhost:8000/api/employees/4
###
PUT http://localhost:8000/api/employees/1
Content-Type: application/json

{
    "first_name": "John 1",
    "last_name": "Doe 1",
    "gender": "Male",
    "birthday": "1990-01-01",
    "date_hired": "2020-01-01",
    "salary": 50000
}
###
DELETE http://localhost:8000/api/employees/1

###
GET http://localhost:8000/api/pensioners
###
POST http://localhost:8000/api/pensioners
Content-Type: application/json

{
    "serial_number": "PEN123456",
    "first_name": "Jane",
    "last_name": "Doe 1",
    "middle_name": "dfhg",
    "pension_account": "1234567890",
    "rank": "PFC",
    "bank_name": "Bank of America",
    "amount": 1500.00,
    "amount_centavos": 150000,
    "retirement_date": "2020-01-01",
    "created_at": "2024-01-01T00:00:00Z",
    "updated_at": "2024-01-01T00:00:00Z"
}